spring:
  h2.console.enabled: true
  #  profiles.active: filtered
  datasource:
    url: @datasource.url@
    username: @datasource.username@
    password: @englishlanguage.datasource.password@
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      # this compels hibernate to use whatever name is in the @Column
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties.hibernate:
      #      #this will format the sql that's written to the log
      format_sql: true
      #      #this compels hibernate to qualify identifiers, permitting reserved names
      globally_quoted_identifiers: true
    #   #write the sql that hibernate generates to the log
    show-sql: false
#    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  security.oauth2.client.registration.azure:
    client-id: 8a97f476-d0b7-4754-bf13-88a08e03ff54
    client-secret: FEK7Q~_e5DZM2wKLUmiV7rMJVIgOAv-g1eqfZ
    redirect-uri: https://hls.education.vermont.gov/